export const REQUEST_SEARCH_ARTICLES = 'REQUEST_SEARCH_ARTICLES';
export const REQUEST_SEARCH_ARTICLES_ERROR = 'REQUEST_SEARCH_ARTICLES_ERROR';
export const RECEIVE_SEARCH_ARTICLES = 'RECEIVE_SEARCH_ARTICLES';
export const REQUEST_DETAILS = 'REQUEST_DETAILS';
export const REQUEST_DETAILS_ERROR = 'REQUEST_DETAILS_ERROR';
export const RECEIVE_DETAILS = 'RECEIVE_DETAILS';
